import type { Metadata } from 'next'
import './globals.css'
import { ChordProvider } from './contexts/chord-context'
import { AnalyticsLayout } from './components/analytics-layout'
import { CartProvider } from './contexts/cart-context'
import { CartButton } from './components/cart-button'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <ChordProvider>
          <CartProvider>
            <AnalyticsLayout>
              {children}
              <CartButton />
            </AnalyticsLayout>
          </CartProvider>
        </ChordProvider>
      </body>
    </html>
  )
}
